import moment from "moment";
export default {
  data() {
    return {
      columnsOrders: [
        {
          title: "ID",
          slots: { title: "customTitle" },
          scopedSlots: { customRender: "orderId" },
          className: "column-service",
        },
        {
          title: "Название",
          dataIndex: "name",
          scopedSlots: { customRender: "name" },
          className: "column-name",
          key: "name",
          width: "300px",
        },
        {
          title: "Дата",
          dataIndex: "created_at",
          scopedSlots: { customRender: "created_at" },
          customRender: (text) => moment(text).format("DD.MM.YYYY"),
          className: "column-date",
        },
        {
          title: "Цена",
          dataIndex: "price",
          // scopedSlots: { customRender: "price" },
          customRender: (text) => `${text ? text : "По договоренности"}`,
          className: "column-client",
          key: "price",
        },

        {
          title: "Срок",
          dataIndex: "deadline",
          scopedSlots: { customRender: "deadline" },
          customRender: (text) => `${text ? text : "По договоренности"}`,
          className: "column-name",
          key: "deadline",
        },
        {
          title: "Категория",
          dataIndex: "category",
          scopedSlots: { customRender: "category" },
          className: "column-name",
          key: "category",
        },
        {
          title: "статус",
          scopedSlots: { customRender: "status" },
          className: "column-tags",
          key: "status",
        },
        {
          title: "фрилансер - ID",
          dataIndex: "selected_request",
          scopedSlots: { customRender: "selected_request" },
          customRender: (text) =>
            text ? `${text.freelancer?.name} - ${text.freelancer?.id}` : "----",
          className: "column-client",
          key: "selected_request",
        },
        {
          title: "Продавец - ID",
          dataIndex: "client",
          scopedSlots: { customRender: "client" },
          customRender: (text) => `${text?.name} - ${text?.id}`,
          className: "column-client",
          key: "client",
        },
        {
          title: "ДЕЙСТВИЯ",
          key: "id",
          dataIndex: "id",
          scopedSlots: { customRender: "btns" },
          className: "column-btns",
          width: "100px",
          align: "center",
        },
      ],
      columnsFreelancers: [
        {
          title: "ID",
          slots: { title: "customTitle" },
          scopedSlots: { customRender: "orderId" },
          className: "column-service",
        },
        {
          title: "F.I.SH",
          dataIndex: "name",
          scopedSlots: { customRender: "name" },
          className: "column-name",
          key: "name",
        },
        {
          title: "Номер телефона",
          dataIndex: "phone",
          scopedSlots: { customRender: "phone" },
          customRender: (text) => "+" + text,
          className: "column-name",
          key: "phone",
        },
        {
          title: "Возраст",
          dataIndex: "age",
          scopedSlots: { customRender: "age" },
          className: "column-client",
          key: "age",
        },
        {
          title: "Область",
          dataIndex: "region",
          scopedSlots: { customRender: "region" },
          customRender: (text) => (text ? text?.name_ru : "----"),
          className: "column-name",
        },

        {
          title: "Специальности",
          dataIndex: "specialities",
          scopedSlots: { customRender: "specialities" },
          className: "column-name",
          key: "specialities",
        },
        {
          title: "Дата регистрации",
          dataIndex: "register_at",
          scopedSlots: { customRender: "register_at" },
          customRender: (text) => moment(text).format("DD.MM.YYYY"),
          className: "column-date",
          key: "register_at",
        },
        {
          title: "Рейтинг",
          dataIndex: "rating",
          scopedSlots: { customRender: "rating" },
          className: "column-name",
          customRender: (text) => Math.ceil(text),
          key: "rating",
        },
        {
          title: "Актив",
          dataIndex: "online",
          scopedSlots: { customRender: "online" },
          className: "column-tags",
          key: "online",
        },
        {
          title: "ДЕЙСТВИЯ",
          key: "id",
          dataIndex: "id",
          scopedSlots: { customRender: "btns" },
          className: "column-btns",
          width: "100px",
          align: "center",
        },
      ],
      columnsSellers: [
        {
          title: "ID",
          slots: { title: "customTitle" },
          scopedSlots: { customRender: "orderId" },
          className: "column-service",
        },
        {
          title: "F.I.SH",
          dataIndex: "name",
          scopedSlots: { customRender: "name" },
          className: "column-name",
          key: "name",
        },
        {
          title: "КОЛ-ВО",
          dataIndex: "ordersCount",
          scopedSlots: { customRender: "ordersCount" },
          className: "column-name",
          key: "ordersCount",
        },
        {
          title: "Дата регистрации",
          dataIndex: "date",
          scopedSlots: { customRender: "date" },
          className: "column-date",
          key: "date",
        },
        {
          title: "статус",
          dataIndex: "status",
          scopedSlots: { customRender: "status" },
          className: "column-tags",
          key: "status",
        },
        {
          title: "ДЕЙСТВИЯ",
          key: "id",
          dataIndex: "id",
          scopedSlots: { customRender: "btns" },
          className: "column-btns",
          width: "100px",
          align: "center",
        },
      ],
      columnsOrderApp: [
        {
          title: "ID",
          slots: { title: "customTitle" },
          scopedSlots: { customRender: "orderId" },
          className: "column-service",
        },
        {
          title: "Имя фрилансера",
          dataIndex: "freelancer",
          scopedSlots: { customRender: "freelancer" },
          customRender: (text) => text?.name,
          className: "column-name",
          key: "freelancer",
        },

        {
          title: "Дата предложения",
          dataIndex: "created_at",
          scopedSlots: { customRender: "created_at" },
          className: "column-date",
          customRender: (text) => moment(text).format("DD.MM.YYYY"),
          key: "created_at",
        },
        {
          title: "Срок",
          dataIndex: "deadline",
          scopedSlots: { customRender: "deadline" },
          customRender: (text) => `${text ? text : "По договоренности"}`,
          className: "column-name",
          key: "deadline",
        },
        {
          title: "Цена",
          dataIndex: "price",
          scopedSlots: { customRender: "price" },
          className: "column-name",
          key: "orders-count",
        },
        {
          title: "Текст ",
          scopedSlots: { customRender: "text" },
          className: "column-name",
          key: "text",
        },

        {
          title: "ДЕЙСТВИЯ",
          key: "id",
          dataIndex: "id",
          scopedSlots: { customRender: "btns" },
          className: "column-btns",
          width: "100px",
          align: "center",
        },
      ],
      columnsComp: [
        {
          title: "ID",
          slots: { title: "customTitle" },
          scopedSlots: { customRender: "orderId" },
          className: "column-service",
        },
        {
          title: "Имя фрилансера",
          dataIndex: "freelancer",
          scopedSlots: { customRender: "freelancer" },
          className: "column-name",
          key: "freelancer",
        },

        {
          title: "Дата",
          dataIndex: "created_at",
          scopedSlots: { customRender: "created_at" },
          customRender: (text) => moment(text).format("DD.MM.YYYY"),
          className: "column-date",
          key: "created_at",
        },
        {
          title: "Текст ",
          scopedSlots: { customRender: "text" },
          className: "column-name",
        },

        {
          title: "ДЕЙСТВИЯ",
          key: "id",
          dataIndex: "id",
          scopedSlots: { customRender: "btns" },
          className: "column-btns",
          width: "100px",
          align: "center",
        },
      ],
    };
  },
};
