import moment from "moment/moment";
export const columnsOrders = [
    {
        title: "ID",
        slots: {title: "customTitle"},
        scopedSlots: {customRender: "orderId"},
        className: "column-service",
        fixed: "left",
        width: "60px",
    },
    {
        title: "Название",
        scopedSlots: {customRender: "name"},
        className: "column-name cursor-pointer",
        width: "250px",
        fixed: "left",
    },
    {
        title: "Дата",
        dataIndex: "created_at",
        scopedSlots: {customRender: "created_at"},
        customRender: (text) => moment(text).format("DD.MM.YYYY"),
        className: "column-date",
    },
    {
        title: "Цена",
        dataIndex: "price",
        // scopedSlots: { customRender: "price" },
        customRender: (text) => `${text ? text : "----"}`,
        className: "column-client",
        key: "price",
    },

    {
        title: "Срок",
        dataIndex: "deadline",
        scopedSlots: {customRender: "deadline"},
        customRender: (text) => `${text ? text : "----"}`,
        className: "column-name",
        key: "deadline",
    },
    {
        title: "Специальности",
        dataIndex: "specialities",
        scopedSlots: {customRender: "specialities"},
        className: "column-name",
        key: "specialities",
        align: "center",
    },
    {
        title: "статус",
        scopedSlots: {customRender: "status"},
        className: "column-tags",
        key: "status",
        align: "center",
    },

    {
        title: "Продавец - ID",
        dataIndex: "user",
        scopedSlots: {customRender: "user"},
        customRender: (text) => `${text?.name} - ${text?.id}`,
        className: "column-client",
        key: "user",
    },
    {
        title: "Кол-во заявок",
        dataIndex: "requests",
        scopedSlots: {customRender: "requests"},
        customRender: (text) => text?.length || 0,
        className: "column-name",
        key: "requests",
        align: "center",
    },
    {
        fixed: "right",
        title: "ДЕЙСТВИЯ",
        key: "id",
        dataIndex: "id",
        scopedSlots: {customRender: "btns"},
        className: "column-btns",
        width: "100px",
        align: "center",
    },
]
